[workspace]
members = ["lib", "cli", "ipc"]
default-members = ["lib", "cli", "ipc"]
resolver = "3"

[workspace.package]
version = "0.5.1"
edition = "2024"
description = "A customizable wallpaper daemon for per-monitor cycling, one-shot application, and optional theme synchronization for Waybar and terminals."
readme = "README.md"
authors = ["T. Sawyer <saylesss87@proton.me>"]
license = "Apache-2.0"
repository = "https://github.com/saylesss88/randpaper"
homepage = "https://github.com/saylesss88/randpaper"
keywords = ["rust", "wallpaper"]
categories = ["command-line-utilities", "multimedia"]
exclude = [
	"assets/*",
	"*.mp4",
	"*.gif",
	".github",
	".gitignore",
	"flake",
	"flake.lock",
	"flake.nix",
	"result",
	"rustfmt.toml",
	"node_modules/*",
	"package-lock.json",
	"package.json",
]

[workspace.dependencies]
anyhow = {version = "1.0.104", default-features = false}
async-trait = "0.1.91"
clap = {version = "4.6.4", features = ["derive"]}
color-thief = {version = "0.2.2"}
dirs = "6.0.0"
env_logger = {version = "0.11.11", default-features = false}
figment = {version = "0.10.19", features = ["env", "toml"]}
fslock = "0.2.1"
humantime = "2.4.0"
image = {version = "0.25.10", default-features = false, features = [
	"png",
	"jpeg",
	"bmp",
	"webp",
]}
log = "0.4.33"
rand = "0.10.2"
serde = {version = "1.0.229", default-features = false}
serde_json = "1.0.151"
smithay-client-toolkit = {version = "0.21.1", default-features = false}
swayipc-async = "3.0.0"
tokio = {version = "1.53.1", features = [
	"io-util",
	"macros",
	"net",
	"process",
	"rt-multi-thread",
	"signal",
	"sync",
	"time",
]}
walkdir = "2.5.0"
wayland-client = {version = "0.31.15"}
xdg = "3.0.0"
randpaper_lib = {path = "lib", version = "0.2.1"}
randpaper_ipc = {path = "ipc", version = "0.1.1"}

[workspace.lints.rust]
unsafe_code = "forbid"
future_incompatible = {level = "warn", priority = -1}
nonstandard_style = {level = "warn", priority = -1}
rust_2018_idioms = {level = "warn", priority = -1}

[workspace.lints.rustdoc]
all = "warn"

[workspace.lints.clippy]
all = {level = "warn", priority = -1}
pedantic = {level = "warn", priority = -1}
nursery = {level = "warn", priority = -1}
# missing_const_for_fn = "allow"
cargo = {level = "warn", priority = -1}

unwrap_used = "warn"
expect_used = "warn"
todo = "warn"
dbg_macro = "warn"
panic = "warn"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 8
panic = 'abort'
strip = true
