[package]
name = "randpaper"
default-run = "randpaper"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true
keywords.workspace = true
readme.workspace = true

# [[bin]]
# name = "randpaper"
# path = "src/main.rs"

[features]
default = ["theming", "waybar", "terminals", "native-renderer"]
native-renderer = ["randpaper_lib/native-renderer"]
theming = ["dep:color-thief", "dep:image"]
waybar = ["theming"]
terminals = ["theming"]

[dependencies]
randpaper_lib = {workspace = true, features = ["native-renderer"]}
randpaper_ipc.workspace = true
anyhow.workspace = true
async-trait.workspace = true
clap.workspace = true
color-thief = {workspace = true, optional = true}
dirs.workspace = true
env_logger.workspace = true
figment.workspace = true
fslock.workspace = true
humantime.workspace = true
image = {workspace = true, optional = true}
log.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
swayipc-async.workspace = true
tokio.workspace = true
walkdir.workspace = true
xdg.workspace = true
