[package]
name = "randpaper_ipc"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"
description = "Randpaper's inter process communication"
keywords = ["wayland", "wallpaper", "layer-shell", "wlroots", "compositor"]

[lib]
name = "randpaper_ipc"
path = "src/lib.rs"

[dependencies]
tokio.workspace = true
xdg.workspace = true
log.workspace = true
thiserror = {version = "2.0.18", default-features = false}
