use anyhow::Context;
use std::fmt::Write;
use std::fs;
use std::path::Path;

pub fn update_theme_file(image_path: &Path) -> anyhow::Result<()> {
    // 1. Open and decode the image
    let img = image::open(image_path).context("Failed to open image for theming")?;

    // 2. Prepare data for color-thief
    // We downscale heavily for speed; we don't need 4k resolution to find a palette
    let img = img.resize(300, 300, image::imageops::FilterType::Nearest);
    let buffer = img.to_rgb8();
    let _width = buffer.width();
    let _height = buffer.height();
    let raw_pixels = buffer.as_raw();

    // 3. Extract Palette
    // We ask for 16 colors to fill standard (0-7) and bright (8-15) slots
    let palette = color_thief::get_palette(
        raw_pixels,
        color_thief::ColorFormat::Rgb,
        10, // Quality (1 is best/slowest, 10 is fast)
        8,  // Number of colors we want
    )
    .map_err(|e| anyhow::anyhow!("Color thief error: {e:?}"))?;

    // Initialize config strings
    let mut ghostty = String::from("# Auto-generated by randpaper\n");
    let mut kitty = String::from("# Auto-generated by randpaper\n");
    let mut foot = String::from("# Auto-generated by randpaper\n[colors]\n");

    // 4. Format as Shell Variables
    // let mut shell_script = String::from("# Generated by randpaper\n");

    for (i, color) in palette.iter().enumerate() {
        // Format hex once: "aabbcc"
        let hex = format!("{:02x}{:02x}{:02x}", color.r, color.g, color.b);

        // Ghostty: palette = 0=#aabbcc
        let _ = writeln!(ghostty, "palette = {i}=#{hex}");

        // Kitty: color0 #aabbcc
        let _ = writeln!(kitty, "color{i} #{hex}");

        // Foot: regular0=aabbcc / bright0=aabbcc
        if i < 8 {
            let _ = writeln!(foot, "regular{i}={hex}");
        } else {
            let _ = writeln!(foot, "bright{}={hex}", i - 8);
        }
    }

    // 5. Background / Foreground Logic
    // Using color 0 for background and color 7 (white-ish) for foreground
    if let (Some(bg), Some(fg)) = (palette.first(), palette.get(7)) {
        let bg_hex = format!("{:02x}{:02x}{:02x}", bg.r, bg.g, bg.b);
        let fg_hex = format!("{:02x}{:02x}{:02x}", fg.r, fg.g, fg.b);

        let _ = writeln!(ghostty, "background = #{bg_hex}\nforeground = #{fg_hex}");
        let _ = writeln!(kitty, "background #{bg_hex}\nforeground #{fg_hex}");
        let _ = writeln!(foot, "background={bg_hex}\nforeground={fg_hex}");
    }

    // 6. Write files to ~/.config/randpaper/themes/
    let config_dir = dirs::config_dir()
        .ok_or_else(|| anyhow::anyhow!("Could not find config directory"))?
        .join("randpaper/themes");

    fs::create_dir_all(&config_dir)?;

    let ghostty_path = config_dir.join("ghostty.config");
    let kitty_path = config_dir.join("kitty.conf");
    let foot_path = config_dir.join("foot.ini");

    fs::write(&ghostty_path, ghostty)?;
    fs::write(&kitty_path, kitty)?;
    fs::write(&foot_path, foot)?;

    log::info!("Updated themes in {}", config_dir.display());

    Ok(())
}
